SELECT 
	p.acto,
	p.dema,
    m.* FROM PROC p
INNER JOIN MOVI m ON m.PROC = p.PROC
WHERE p.ACTO = 'GONZALEZ NATALIA MARIBEL' ORDER BY m.FECH DESC;





SELECT 
	m.movi,
    m.* FROM PROC p
INNER JOIN MOVI m ON m.PROC = p.PROC
WHERE p.ACTO = 'MISKINICH FLAVIO FERNANDO' ORDER BY m.FECH DESC;

SELECT * FROM MOVI WHERE DSCR LIKE 'INTIMAN A 3 DIAS A SUBIR DE FORMA LEGIBLE EL EMG';

SELECT TIPO AS ti, 
       count(DISTINCT TIPO) AS cuenta  
FROM movi
GROUP BY ti
   